# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
    - job: job1
      steps:
         - script: echo job1
           displayName: Run online script
    - job: job2
      dependsOn: job1
      steps:
        - script: echo job 2
          displayName: Run online script
  - stage: dev_deploy
    jobs:
    - job: job1
      steps:
         - script: echo job1
           displayName: Run online script
    - job: job2
      dependsOn: job1
      steps:
        - script: echo job 2
          displayName: Run online script
  - stage: QA_deploy
    jobs:
    - job: job1
      steps:
         - script: echo job1
           displayName: Run online script
    - job: job2
      dependsOn: job1
      steps:
        - script: echo job 2
          displayName: Run online script
  - stage: Build222
    jobs:
    - job: job1
      steps:
         - script: echo job1
           displayName: Run online script
    - job: job2
      dependsOn: job1
      steps:
        - script: echo job 2
          displayName: Run online script  
  - stage: prod_deploy
    jobs:
    - job: job1
      steps:
         - script: echo job1
           displayName: Run online script
    - job: job2
      dependsOn: job1
      steps:
        - script: echo job 2
          displayName: Run online script 