# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
stages:
  - stage: Build
    jobs: 
      - job: job1
        steps:
        - bash: echo "Do the build"
  - stage: Dev_deploy
    jobs:
      - deployment: Dev_deploy_job
        environment: Dev
        strategy:
         runOnce:
           deploy:
             steps:
               - script: deploy to dev
  - stage: Qa_deploy
    jobs:
      - deployment: Dev_deploy_job
        environment: Qa
        strategy:
         runOnce:
           deploy:
             steps:
               - script: deploy to qa