# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs: 
  - job: Job_1
    steps:
      - script: echo Hello world
        displayName: Run a online script
  - job: Job_2
    dependsOn: Job_1
    steps:
      - script: echo Hello world
        displayName: Run a online script
  
  - job: Job_3
    steps:
      - script: echo Hello world
        displayName: Run a online script
  
  - job: Job_4
    dependsOn: Job_3
    steps:
      - script: echo Hello world
        displayName: Run a online script