# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
 
  - stage: Build
    jobs:
      - job: First_job
        steps:
         - bash: echo $(Agent.BuildDirectory)
         - bash: echo $(Build.TriggeredBy.BuildNumber)
         - bash: echo $(Strategy.CycleName)
         - bash: echo $(Build.BuildNumber)
         - bash: echo $(Build.BuildId)
         - bash: echo $(Build.Repository.ID)
         - bash: echo $(Build.SourceVersionMessage)
         - bash: echo $(Build.TriggeredBy.BuildNumber)
         - bash: ls -a $(Build.SourcesDirectory)
           displayName: first job is success
      - job: Secon_job
        steps:
          - bash: echo Second job in Build stage
  - stage: Dev_deploy
    dependsOn: Build
    jobs:
      - job: First_job
        steps:
          - script: echo dev Stage
      - job: Secon_job
        steps:
          - bash: echo Second job in Dev-deploy
  - stage: QA
    dependsOn: Build
    jobs:
      - job: First_job
        steps:
          - script: echo QA Stage
      - job: Secon_job
        steps:
          - bash: echo Second job in QA stage
  - stage: Prod
    jobs:
      - job: First_job
        steps:
          - script: echo Prod Stage
      - job: Secon_job
        steps:
          - bash: echo Second job in Prod stage
